In [1]:
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

Dados capturados em 14 de Dezembro de 2021. Importação dos dados feita em 14 de Dezembro de 2021 às 20:32:28.

[dicionário dos dados](https://github.com/turicas/covid19-br/blob/master/api.md#caso_full)

## Limpando os dados

[dicionário de dados](https://github.com/turicas/covid19-br/blob/master/api.md#caso_full)

In [2]:
caso_full = pd.read_csv('./dados/dados_brutos/caso_full.csv')

In [3]:
caso_full_sp = caso_full.query('state=="SP"')
caso_full_sp.to_csv('./dados/dados_brutos/caso_full.csv', index=False)

In [4]:
caso_full_sp.head()

,city,city_ibge_code,date,epidemiological_week,estimated_population,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
0,São Paulo,3550308.0,2020-02-25,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-25,0.0,0,1,city,SP,1,0
1,NaN,35.0,2020-02-25,202009,46289333.0,45919049.0,False,False,1,0.00216,2020-02-25,0.0,0,1,state,SP,1,0
2,São Paulo,3550308.0,2020-02-26,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-26,0.0,0,2,city,SP,0,0
3,NaN,35.0,2020-02-26,202009,46289333.0,45919049.0,False,False,1,0.00216,2020-02-26,0.0,0,2,state,SP,0,0
4,São Paulo,3550308.0,2020-02-27,202009,12325232.0,12252023.0,False,False,1,0.00811,2020-02-27,0.0,0,3,city,SP,0,0

Vamos delimitar os nossos estudos na região metropolitana do vale do paraíba e litoral norte, interior do estado de São Paulo. Essa região ainda é dividia em mais 5 sub

https://www.emtu.sp.gov.br/emtu/institucional/quem-somos/vale-do-paraiba-e-litoral-norte.fss

In [5]:
vale_do_paraiba = ['Caçapava', 'Igaratá', 'Jacareí', 'Jambeiro', 'Monteiro Lobato',
                   'Paraibuna', 'Santa Branca', 'São José dos Campos', 'Campos do Jordão',
                   'Lagoinha', 'Natividade da Serra', 'Pindamonhangaba', 'Redenção da Serra',
                   'Santo Antônio do Pinhal', 'São Bento do Sapucaí', 'São Luiz do Paraitinga',
                   'Taubaté', 'Tremembé', 'Aparecida', 'Cachoeira Paulista', 'Canas', 'Cunha',
                   'Guaratinguetá', 'Lorena', 'Piquete', 'Potim', 'Roseira', 'Arapeí', 'Areias',
                   'Bananal', 'Cruzeiro', 'Lavrinhas', 'Queluz', 'São José do Barreiro', 
                   'Silveiras', 'Caraguatatuba', 'Ilhabela', 'São Sebastião', 'Ubatuba'
                   ]

In [6]:
df_vale_do_paraiba = caso_full_sp.query('city in @vale_do_paraiba')

In [7]:
df_vale_do_paraiba.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23906 entries, 88 to 396485
Data columns (total 18 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   city                                           23906 non-null  object
 1   city_ibge_code                                 23906 non-null  float64
 2   date                                           23906 non-null  object
 3   epidemiological_week                           23906 non-null  int64
 4   estimated_population                           23906 non-null  float64
 5   estimated_population_2019                      23906 non-null  float64
 6   is_last                                        23906 non-null  bool
 7   is_repeated                                    23906 non-null  bool
 8   last_available_confirmed                       23906 non-null  int64
 9   last_available_confirmed_per_100k_inhabitants  23863 non-null  float64
 10  last_available_date                            23906 non-null  object
 11  last_available_death_rate                      23906 non-null  float64
 12  last_available_deaths                          23906 non-null  int64
 13  order_for_place                                23906 non-null  int64
 14  place_type                                     23906 non-null  object
 15  state                                          23906 non-null  object
 16  new_confirmed                                  23906 non-null  int64
 17  new_deaths                                     23906 non-null  int64
dtypes: bool(2), float64(5), int64(6), object(5)
memory usage: 3.1+ MB

Observando os dados gerais desse novo dataset, vemos que ele não possui dados nulos.

In [8]:
df_vale_do_paraiba.tail()

,city,city_ibge_code,date,epidemiological_week,estimated_population,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
396439,São Luiz do Paraitinga,3550001.0,2022-01-05,202201,10690.0,10687.0,False,True,948,8868.10103,2021-12-06,0.0285,27,609,city,SP,0,0
396446,São Sebastião,3550704.0,2022-01-05,202201,90328.0,88980.0,False,True,8112,8980.60402,2021-12-06,0.0212,172,652,city,SP,0,0
396468,Taubaté,3554102.0,2022-01-05,202201,317915.0,314924.0,False,True,29107,9155.59190,2021-12-06,0.0348,1013,658,city,SP,0,0
396477,Tremembé,3554805.0,2022-01-05,202201,47714.0,47185.0,False,True,2739,5740.45354,2021-12-06,0.0208,57,603,city,SP,0,0
396485,Ubatuba,3555406.0,2022-01-05,202201,91824.0,90799.0,False,True,8110,8832.11361,2021-12-06,0.0168,136,633,city,SP,0,0

Agora que delimitamos o nosso dataset, precisamos verificar a consistência dos dados. Conforme explicado pelo Brasil IO, os registros dependem da divulgação dos municípios, o que pode não acontecer todos os dias. Para verificarmos se os registros são do dia, precisamos olhar algumas colunas:
* `is_repeated`:  Se o registro é referente ao boletim do dia ou foi copiado do último registro disponível.
* `is_last`: Se o registro é o mais novo para o local. 
* `last_available_date`: O último dia em que a cidade emitiu o boletim.


Vamos avaliar quais foram as ultimas atualizações por cidade.

In [9]:
df_vale_do_paraiba.groupby('city')[['last_available_date']].last()

                        last_available_date
city
Aparecida                        2021-12-06
Arapeí                           2021-12-06
Areias                           2021-12-06
Bananal                          2021-12-06
Cachoeira Paulista               2021-12-06
Campos do Jordão                 2021-12-06
Canas                            2021-12-06
Caraguatatuba                    2021-12-06
Caçapava                         2021-12-06
Cruzeiro                         2021-12-06
Cunha                            2021-12-06
Guaratinguetá                    2021-12-06
Igaratá                          2021-12-06
Ilhabela                         2021-12-06
Jacareí                          2021-12-06
Jambeiro                         2021-12-06
Lagoinha                         2021-12-06
Lavrinhas                        2021-12-06
Lorena                           2021-12-06
Monteiro Lobato                  2021-12-06
Natividade da Serra              2021-12-06
Paraibuna                        2021-12-06
Pindamonhangaba                  2021-12-06
Piquete                          2021-12-06
Potim                            2021-12-06
Queluz                           2021-12-06
Redenção da Serra                2021-12-06
Roseira                          2021-12-06
Santa Branca                     2021-12-06
Santo Antônio do Pinhal          2021-12-06
Silveiras                        2021-12-06
São Bento do Sapucaí             2021-12-06
São José do Barreiro             2021-12-06
São José dos Campos              2021-12-06
São Luiz do Paraitinga           2021-12-06
São Sebastião                    2021-12-06
Taubaté                          2021-12-06
Tremembé                         2021-12-06
Ubatuba                          2021-12-06

A última atualização dos dados na região foi 26/10/21. Isso quer dizer que todos os dados a frente dessa data mantém a mesma quantidade de casos. Como já se passaram mais de 2 meses e a recomendação no Brasil IO é utilizar dados de até 30 anterior à última atualização para se ter consistência dos dados, podemos disconsiderar os dados do mes de Outubro/21.

In [10]:
#Transformando a coluna date em data
df_vale_do_paraiba['date'] = pd.to_datetime(df_vale_do_paraiba['date'], format='%Y-%m-%d')

#Filtrar o dataset para que tenha os registros até 30 de setembro de 2021
df_vale_2021 = df_vale_do_paraiba[df_vale_do_paraiba['date'] <= '2021-09-30']
df_vale_2021 = df_vale_2021.reset_index()
df_vale_2021.drop('index', axis=1, inplace=True)
df_vale_2021.head()

,city,city_ibge_code,date,epidemiological_week,estimated_population,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,order_for_place,place_type,state,new_confirmed,new_deaths
0,São José dos Campos,3549904.0,2020-03-18,202012,729737.0,721944.0,False,False,1,0.13704,2020-03-18,0.0,0,1,city,SP,1,0
1,São José dos Campos,3549904.0,2020-03-19,202012,729737.0,721944.0,False,True,1,0.13704,2020-03-18,0.0,0,2,city,SP,0,0
2,Taubaté,3554102.0,2020-03-19,202012,317915.0,314924.0,False,False,1,0.31455,2020-03-19,0.0,0,1,city,SP,1,0
3,São José dos Campos,3549904.0,2020-03-20,202012,729737.0,721944.0,False,False,1,0.13704,2020-03-20,0.0,0,3,city,SP,0,0
4,Taubaté,3554102.0,2020-03-20,202012,317915.0,314924.0,False,False,1,0.31455,2020-03-20,0.0,0,2,city,SP,0,0

In [11]:
df_vale_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20123 entries, 0 to 20122
Data columns (total 18 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   city                                           20123 non-null  object
 1   city_ibge_code                                 20123 non-null  float64
 2   date                                           20123 non-null  datetime64[ns]
 3   epidemiological_week                           20123 non-null  int64
 4   estimated_population                           20123 non-null  float64
 5   estimated_population_2019                      20123 non-null  float64
 6   is_last                                        20123 non-null  bool
 7   is_repeated                                    20123 non-null  bool
 8   last_available_confirmed                       20123 non-null  int64
 9   last_available_confirmed_per_100k_inhabitants  20080 non-null  float64
 10  last_available_date                            20123 non-null  object
 11  last_available_death_rate                      20123 non-null  float64
 12  last_available_deaths                          20123 non-null  int64
 13  order_for_place                                20123 non-null  int64
 14  place_type                                     20123 non-null  object
 15  state                                          20123 non-null  object
 16  new_confirmed                                  20123 non-null  int64
 17  new_deaths                                     20123 non-null  int64
dtypes: bool(2), datetime64[ns](1), float64(5), int64(6), object(4)
memory usage: 2.5+ MB

Agora vamos avaliar quais colunas serão úteis para a nossa análise, apoiado na [documentação do dataset](https://github.com/turicas/covid19-br/blob/master/api.md#caso_full)

In [12]:
df_vale_2021[df_vale_2021['is_last'] == True]

Empty DataFrame
Columns: [city, city_ibge_code, date, epidemiological_week, estimated_population, estimated_population_2019, is_last, is_repeated, last_available_confirmed, last_available_confirmed_per_100k_inhabitants, last_available_date, last_available_death_rate, last_available_deaths, order_for_place, place_type, state, new_confirmed, new_deaths]
Index: []

In [13]:
df_vale_2021[['place_type']].value_counts()

place_type
city          20123
dtype: int64

In [14]:
df_vale_2021[['state']].value_counts()

state
SP       20123
dtype: int64

As colunas a serem eliminadas:
* `city_ibge_code` traz o código IBGE do local - não será útil na nossa análse;
* `estimated_population_2019` traz a estimativa da população para a cidade/estado em 2019 segundo o IBGE, mas como a coluna possui dados desatualizados a própria documentação indica usar a coluna `estimated_population`;
* `is_last` indica se o registro é o mais novo para esse local, mas como quando extraímos a base de dados o registro mais novo era 26/10, para esse nosso sub dataset toda a coluna será falso, então podemos eliminar essa coluna.
* `place_type` indica se o registro se refere à uma cidade ou um estado. Como estamos lidando somente com estados, não vamos utilizar essa coluna;
* `state` traz a sigla da unidade federativa e como todas as cidades são do estado de São Paulo essa colna também não é necessária.

In [15]:
colunas_para_retirar = ['city_ibge_code', 'estimated_population_2019', 'is_last', 
                        'place_type', 'state']

In [16]:
df_vale_2021.drop(colunas_para_retirar, axis=1, inplace=True)

In [17]:
#Salvar o dataset num novo arquivo csv.
df_vale_2021.to_csv('./dados/dados_limpos/vale_do_paraiba.csv', index=False, 
                    date_format='%Y-%m-%d', )